repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args:
          [
            "--rcfile=.pylintrc", # Link to your config file
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.960'
    hooks:
      - id: mypy
        stages: [ push ]